# permissions for end users to view kibanas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kibana-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: es-operator
    app.kubernetes.io/part-of: es-operator
    app.kubernetes.io/managed-by: kustomize
  name: kibana-viewer-role
rules:
- apiGroups:
  - db.alongparty.cn
  resources:
  - kibanas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.alongparty.cn
  resources:
  - kibanas/status
  verbs:
  - get
