apiVersion: db.alongparty.cn/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch-sample
    app.kubernetes.io/part-of: es-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: es-operator
  name: elasticsearch-sample
spec:
  # TODO(user): Add fields here
  size: 3
  image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
  resource:
    limits:
      memory: 1G
  config:
    bootstrap.memory_lock: false
    bootstrap.system_call_filter: false
    http.port:  9200
    transport.port:  9300
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    cluster.routing.allocation.same_shard.host: true
    indices.query.bool.max_clause_count : 2048
    indices.memory.index_buffer_size: 30%
    indices.fielddata.cache.size: 40%
    indices.breaker.fielddata.limit: 70%
    indices.recovery.max_bytes_per_sec: 20mb
    indices.breaker.total.use_real_memory: false
    thread_pool.write.queue_size: 1000
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - elasticsearch
            topologyKey: kubernetes.io/os